### ISSUE TITLE
[FeatureRequest] VMP/PSV  Export/Signing (Reverse engineered in 2019!)

### ISSUE THREAD

**Issue by wmxp** [sithlord48/blackchocobo#11]
This is a super unimportant request, but if you are feeling up for a fun challenge - after 12 bloody years, a team of guys finally cracked the PSV format and made a signing tool for it along with the the VMP format that PSP / Vita uses. If you're interested:

https://github.com/dots-tb/vita-mcr2vmp

https://github.com/dots-tb/ps3-psvresigner

https://github.com/PMStanley/PSV-Exporter

**Comment by myst6re** [comment]
This is awesome! Thanks for sharing! I opened an issue on my project too https://github.com/myst6re/hyne/issues/20

**Comment by wmxp** [comment]
Just another side note if you're interested, but the commercial product [Save Wizard for PS4 Max](https://www.savewizard.net/) has an advanced mode which strips the save files from their encrypted containers, allowing you to import and export the base save. The save files from FF7 PS4 are 100% identical to the PC release the port is based on.

![FF7_SW](https://user-images.githubusercontent.com/30638431/72557830-602b1300-3856-11ea-8ca4-92848b850523.png)


I easily converted PS1 saves to PC format with Black Chocobo and then imported them into the PS4 version with SW, or vice versa.

**Comment by sithlord48** [comment]
This is great news!
I have issues open for ff7tk for most of these. I;ll close this and point you to them 

PSV signing has been added since about 2016 but we have not been able to provide keys and IV. Now that should be a trivial thing to do so i will update that support 

VMP -  Needs to be added now that i know they are the same crypto. (and will do)
https://github.com/sithlord48/ff7tk/issues/6

PS4  - Need Crypto for this still 
https://github.com/sithlord48/ff7tk/issues/5

XBONE - Bonus Issue if you know any thing about. 
https://github.com/sithlord48/ff7tk/issues/50

**Comment by sithlord48** [comment]
Newer builds will now correctly sign PSV files and allow for export.

**Comment by wmxp** [comment]
A very off topic comment, but in case you missed it, Squeenix FINALLY patched FF7 PS4 in Dec last year to fix the field music restart gltich. FOUR YEARS LATER:
https://wccftech.com/final-fantasy-vii-ps4-patch-1-02-musicbug/
