### ISSUE TITLE
It only shows C Drive

### ISSUE THREAD

**Issue by firecloud42** [sithlord48/blackchocobo#34]
I have everything moved over to my D Drive (Because C drive is for my OS and a few important programs) and Black Chocobo isn't showing anything but C Drive.

**Comment by sithlord48** [comment]
Hello can you provide a bit more info about what your problem is ? 
1. What is the version of Black Chocobo your using? 
2. Have you tried In Options are you using the "Native File Dialog" ? 

The custom file dialog may require you to add a "place" for D: or any specific location you use often for quick access. With out that you should be able to use the combo box in the file dialog to see "My Computer"  and all your drives and browse to any location.

**Comment by sithlord48** [comment]
There is a check box that says "Use Native File dialogs" It is located to the left of the edit places button in settings (if its checked the edit places buttons will not be there). 

In you second screen shot you can access "My Computer" by clicking on the combobox that says "C:\Users\Konabochi" the entry for "My Computer" will be in this list.

I have also made it so in the next release (or continuous build) you will have a list of attached drives shown as part of the list on the left panel.
