### ISSUE TITLE
Missing Cait Sith & Vincent

### ISSUE THREAD

**Issue by rinvelo** [sithlord48/blackchocobo#43]
**Is your feature request related to a problem? Please describe.**
The 3x3 grid of characters omits Cait Sith & Vincent

**Describe the solution you'd like**
Replace the 3x3 grid with a drop-down of which character you want to edit (similar to how the Party Members has a drop-down of all characters)
![image](https://user-images.githubusercontent.com/53977017/186907654-41458859-6470-4a5f-86a5-b0f18d724adf.png)
![image](https://user-images.githubusercontent.com/53977017/186907701-490cf8f7-121d-4d75-b8bc-b7b5b90095ad.png)

**Comment by sithlord48** [comment]
Hi i can't do that since the save only stores 9 characters worth of data.
The 9 you see in the grid represent the 9 the save has. In the default save the space used for cait-sith and vincent are occupied by young cloud and sephiroth in setup for the kalm flash back. This is why you see them when bc starts up since it starts always with the default save when you don't provide a file to open. You can change the id of the characters in the slots Slot 6 and 7 provide a convenance id toggle while the others slots (as well as the ability to change ids freely) is hidden unless you have the charEditor to advanced mode. Becareful if you play with the ids as the game only seams to accept changes for the slots that hold young cloud / cait-sith as well as the vincent/ sephiroth slot.
