### ISSUE TITLE
Gil is signed 32 bit value instead of unsigned.

### ISSUE THREAD

**Issue by DLPB2** [sithlord48/blackchocobo#5]
Maximum gil in FF7 is 4294967295.  Black Chocobo shows wrong value in the save preview window, and caps the value in main editing window.

**Comment by sithlord48** [comment]
The Max for a uint32 is 4294967295. When you sign a number you halve the range since signed the last bit is used for the tracking if positive or negitive..  That being said there is an issue because the QSpinbox used to put this value is behind the scenes a qint32 (32 bit signed int). so its capping the max input to the max value of a 32bit signed int.. I will see how i force that box to store in unsigned

**Comment by myst6re** [comment]
Use a QDoubleSpinBox and call setDecimals(0);
https://github.com/myst6re/hyne/blob/master/SpinBox.cpp

**Comment by sithlord48** [comment]
@myst6re  that is exacty what im doing right now

**Comment by sithlord48** [comment]
Fixed in: https://github.com/sithlord48/blackchocobo/commit/b3de123549beba3cc0193ac4e917c74821ca562e

**Comment by DLPB2** [comment]
so its capping the max input to the max value of a 32bit signed int.
-----
That's what I meant :)  That it was capping to a signed as well.  The preview window seemed to be a different issue (overflow).
